CREATE DATABASE IF NOT EXISTS mamel_db;
CREATE USER IF NOT EXISTS obouizga;
GRANT ALL PRIVILEGES ON mamel_db.* TO obouizga@'%' ;
ALTER USER 'root'@'localhost' IDENTIFIED BY '12345' ;
FLUSH PRIVILEGES;
