version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx/
    image:  nginx:buster
    volumes:
      - wp-volume:/var/www/html
    networks:
      - main-network
    ports:
      - 443:443
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build:
      context: ./requirements/wordpress/
    image: wordpress:buster
    volumes:
      - wp-volume:/var/www/html
    networks: 
      - main-network
    expose:
      - 9000
    env_file:
      - .env
    restart: on-failure
  mariadb:
    build:
      context: ./requirements/mariadb/
    image:  mariadb:buster
    volumes:
      - mariadb-volume:/var/lib/mysql/
    networks:
      - main-network
    expose:
      - 3306
    env_file:
      - .env
    restart: on-failure
networks:
  main-network:
volumes:
    wp-volume:
      driver: local
      driver_opts:
        device: /home/obouizga/data/wordpress
        o: bind
        type: none
    mariadb-volume:
      driver: local
      driver_opts:
        device: /home/obouizga/data/mariadb
        o: bind
        type: none
