version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx/
    image:  nginx
    volumes:
      - wp-volume:/var/www/html
    networks:
      - main-network
    ports:
      - 443:443
    env_file:
      - .env
  wordpress:
    build:
      context: ./requirements/wordpress/
    image: wordpress
    volumes:
      - wp-volume:/var/www/html
    networks: 
      - main-network
    expose:
      - 9000
    env_file:
      - .env
  mariadb:
    build:
      context: ./requirements/mariadb/
    image:  mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql/
    networks:
      - main-network
    expose:
      - 3306
    env_file:
      - .env
networks:
  main-network:
volumes:
    wp-volume:
      driver: local
      driver_opts:
        device: ~/obouizga/data/wordpress
        o: bind
        type: none
    mariadb-volume:
      driver: local
      driver_opts:
        device: ~/obouizga/data/mysql
        o: bind
        type: none